// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPortalApplication.Data;

#nullable disable

namespace StudentPortalApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207145212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentPortalApplication.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            IsActive = false,
                            Name = "Sofware Engineering"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            IsActive = false,
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            IsActive = false,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 2,
                            IsActive = false,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 5,
                            FacultyId = 2,
                            IsActive = false,
                            Name = "Human Resource Management"
                        },
                        new
                        {
                            Id = 6,
                            FacultyId = 2,
                            IsActive = false,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 7,
                            FacultyId = 3,
                            IsActive = false,
                            Name = "Civil"
                        },
                        new
                        {
                            Id = 8,
                            FacultyId = 3,
                            IsActive = false,
                            Name = "Mechanical"
                        },
                        new
                        {
                            Id = 9,
                            FacultyId = 3,
                            IsActive = false,
                            Name = "Chemical"
                        });
                });

            modelBuilder.Entity("StudentPortalApplication.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("StudentPortalApplication.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudentTypeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1998, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "himasha@email.com",
                            FacultyId = 1,
                            FullName = "Himasha Wijewickrama",
                            Gender = "Female",
                            RegistrationDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "maheesha@gmail.com",
                            FacultyId = 1,
                            FullName = "Maheesha Wijewickrama",
                            Gender = "Female",
                            RegistrationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "mandira.l@email.com",
                            FacultyId = 1,
                            FullName = "Mandira Liyanage",
                            Gender = "Female",
                            RegistrationDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1998, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "jib@yahoo.com",
                            FacultyId = 2,
                            FullName = "Jithma Vithanage",
                            Gender = "Female",
                            RegistrationDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1996, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "tilinar@hotmail.com",
                            FacultyId = 2,
                            FullName = "Tilina Ratnayake",
                            Gender = "Male",
                            RegistrationDate = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1993, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "kasun@email.com",
                            FacultyId = 2,
                            FullName = "Kasun Radhitha",
                            Gender = "Male",
                            RegistrationDate = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1996, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "binura@example.com",
                            FacultyId = 3,
                            FullName = "Binura Yasas",
                            Gender = "Male",
                            RegistrationDate = new DateTime(2019, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1990, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "conrad@gmail.com",
                            FacultyId = 3,
                            FullName = "Conrad Fisher",
                            Gender = "Male",
                            RegistrationDate = new DateTime(2017, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1990, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "bellyc@yahoo.com",
                            FacultyId = 3,
                            FullName = "Belly Conklin",
                            Gender = "Female",
                            RegistrationDate = new DateTime(2017, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1994, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ryomans@yahoo.com",
                            FacultyId = 1,
                            FullName = "Ryomen Sukuna",
                            Gender = "Male",
                            RegistrationDate = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentTypeId = 1
                        });
                });

            modelBuilder.Entity("StudentPortalApplication.Models.StudentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "Foreign"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Local"
                        });
                });

            modelBuilder.Entity("StudentPortalApplication.Models.Department", b =>
                {
                    b.HasOne("StudentPortalApplication.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentPortalApplication.Models.Student", b =>
                {
                    b.HasOne("StudentPortalApplication.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentPortalApplication.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalApplication.Models.StudentType", "StudentType")
                        .WithMany("Students")
                        .HasForeignKey("StudentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("StudentType");
                });

            modelBuilder.Entity("StudentPortalApplication.Models.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentPortalApplication.Models.StudentType", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
